version: '3.8'

services:

  sunny:
    image: niceaesthetics/sunny:master
    container_name: sunny
    volumes:
      - ./config.json:/home/appuser/config.json:ro
    extra_hosts:
      - "lavalink:127.0.0.1" # Expose lavalink to container
      - "redis:127.0.0.1" # Expose redis to container

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sunny
